Traceback (most recent call last):
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
save=LTS.sel(lat=45.50, lon=9.36, method='nearest')['min']
save.data.visualize()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m save[38;5;241m=[39mLTS[38;5;241m.[39msel(lat[38;5;241m=[39m[38;5;241m45.50[39m, lon[38;5;241m=[39m[38;5;241m9.36[39m, method[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnearest[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mmin[39m[38;5;124m'[39m]
[0;32m----> 2[0m [43msave[49m[38;5;241;43m.[39;49m[43mdata[49m[38;5;241;43m.[39;49m[43mvisualize[49m[43m([49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/dask/base.py:241[0m, in [0;36mDaskMethodsMixin.visualize[0;34m(self, filename, format, optimize_graph, **kwargs)[0m
[1;32m    197[0m [38;5;28;01mdef[39;00m [38;5;21mvisualize[39m([38;5;28mself[39m, filename[38;5;241m=[39m[38;5;124m"[39m[38;5;124mmydask[39m[38;5;124m"[39m, [38;5;28mformat[39m[38;5;241m=[39m[38;5;28;01mNone[39;00m, optimize_graph[38;5;241m=[39m[38;5;28;01mFalse[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    198[0m     [38;5;124;03m"""Render the computation of this object's task graph using graphviz.[39;00m
[1;32m    199[0m 
[1;32m    200[0m [38;5;124;03m    Requires ``graphviz`` to be installed.[39;00m
[0;32m   (...)[0m
[1;32m    239[0m [38;5;124;03m    https://docs.dask.org/en/latest/optimize.html[39;00m
[1;32m    240[0m [38;5;124;03m    """[39;00m
[0;32m--> 241[0m     [38;5;28;01mreturn[39;00m [43mvisualize[49m[43m([49m
[1;32m    242[0m [43m        [49m[38;5;28;43mself[39;49m[43m,[49m
[1;32m    243[0m [43m        [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mfilename[49m[43m,[49m
[1;32m    244[0m [43m        [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;28;43mformat[39;49m[43m,[49m
[1;32m    245[0m [43m        [49m[43moptimize_graph[49m[38;5;241;43m=[39;49m[43moptimize_graph[49m[43m,[49m
[1;32m    246[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    247[0m [43m    [49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/dask/base.py:801[0m, in [0;36mvisualize[0;34m(filename, traverse, optimize_graph, maxval, engine, *args, **kwargs)[0m
[1;32m    799[0m     [38;5;28;01mreturn[39;00m cytoscape_graph(dsk, filename[38;5;241m=[39mfilename, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    800[0m [38;5;28;01melif[39;00m engine [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 801[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m    802[0m         [38;5;124m"[39m[38;5;124mNo visualization engine detected, please install graphviz or ipycytoscape[39m[38;5;124m"[39m
[1;32m    803[0m     )
[1;32m    804[0m [38;5;28;01melse[39;00m:
[1;32m    805[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mVisualization engine [39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m not recognized[39m[38;5;124m"[39m)

[0;31mRuntimeError[0m: No visualization engine detected, please install graphviz or ipycytoscape
RuntimeError: No visualization engine detected, please install graphviz or ipycytoscape

